version: '3.8'

services:
  app:
    build: .
    container_name: ecommerce_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/ecommerce
      UPSTASH_REDIS_URL: redis://redis:6379
      ACCESS_TOKEN_SECRET: your_access_token_secret
      REFRESH_TOKEN_SECRET: your_refresh_token_secret
      CLOUDINARY_CLOUD_NAME: your_cloud_name
      CLOUDINARY_API_KEY: your_api_key
      CLOUDINARY_API_SECRET: your_api_secret
      STRIPE_SECRET_KEY: your_stripe_secret_key
      CLIENT_URL: http://localhost:5173
      NODE_ENV: development
    depends_on:
      - mongo
      - redis
    command: >
      sh -c "npm install && npm run build && npm run start"

  mongo:
    image: mongo:4.4
    container_name: ecommerce_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: ecommerce_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo_data:
